name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions: write-all  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  SAST:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: none
          queries: |
            security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java-kotlin"    

  SCA:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4    
      - name: Build
        run: |
           mvn package

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: 'ms-catalog-content'  
          path: '.'
          format: 'HTML'
          args: >
             --disableCentral

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          path: ${{github.workspace}}/reports
 
